<a href="https://colab.research.google.com/github/defritonc1/cleanflight/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import TensorFlow
import tensorflow as tf
print (tf.__version__)


2.17.0


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
# Create tesors with tensorfolow
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the numberof dimensions
scalar.ndim


0

In [5]:
# Create a vector
vector = tf.constant([10,10,12])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 12], dtype=int32)>

In [6]:
seed = 42
tf.random.set_seed(
    seed
)
a = tf.random.normal
a

<function tensorflow.python.ops.random_ops.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)>

In [7]:
# check the dimension of our vector
vector.ndim

1

In [8]:
#create a matrix (note: has more thatone dimension)
matrix = tf.constant([[10,7],[10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
#craete another matrix
another_matrix = tf.constant([[12.,7.],[3.,2.],[8.,4.]])
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[12.,  7.],
       [ 3.,  2.],
       [ 8.,  4.]], dtype=float32)>

In [11]:
another_matrix.ndim

2

In [12]:
# Create a Tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

What we have created so far:

  *   Scalar: a single number
  *   Vector: a number with direction(eg Wind speed and direction
  *   Matrix: a 2-dimensional array of things
  *   Tensor: an n-dimensional array of numbers.
  



In [14]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [15]:
v = tf.Variable(1.)
v.assign(2.)


<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

In [16]:
#Create the same tensor with tf.Variable() as abve
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [17]:

 changeable_tensor[1].assign(5)
 print (changeable_tensor[0])
 print (changeable_tensor[1])

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [18]:
# Creating Random Tensors.

✌

In [19]:
# Create 2 random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))

random_2 = tf.random.Generator.from_seed(432)
random_2 = random_2.normal(shape = (3,2))

# are they equal
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.1496083 ,  0.3450742 ],
        [ 0.6620306 ,  1.0915599 ],
        [-1.7731358 ,  0.10161041]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [20]:
# Shuffle a tensor for when the apparent order doesnt affect the outcome
not_shuffled = tf.constant([[10,7],
                            [3,10],
                            [4,3]])

shuffled = tf.random.shuffle(not_shuffled)

shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3, 10],
       [ 4,  3],
       [10,  7]], dtype=int32)>

# **⚒EXERCISE**: Read through TesorFlow documentation on random seed generation:
http://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.


In [21]:
import torch

import numpy as np

a = torch.FloatTensor(300, 200)

a



tensor([[ 1.0580e+13,  4.4568e-41,  1.0580e+13,  ...,  4.4568e-41,
          7.3601e+19,  4.4568e-41],
        [-6.2322e+17,  4.4568e-41, -9.3088e+16,  ...,  4.4567e-41,
         -6.2452e+16,  4.4568e-41],
        [-2.1839e+18,  4.4568e-41,  1.1603e+36,  ...,  4.4568e-41,
          1.0075e+36,  4.4567e-41],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])

In [22]:
a.new_ones

a


tensor([[ 1.0580e+13,  4.4568e-41,  1.0580e+13,  ...,  4.4568e-41,
          7.3601e+19,  4.4568e-41],
        [-6.2322e+17,  4.4568e-41, -9.3088e+16,  ...,  4.4567e-41,
         -6.2452e+16,  4.4568e-41],
        [-2.1839e+18,  4.4568e-41,  1.1603e+36,  ...,  4.4568e-41,
          1.0075e+36,  4.4567e-41],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])

In [23]:
tf.ones([10,7])


<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [24]:
import numpy as np

In [25]:
tf.zeros(shape=(3,4))


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [26]:
numpy_A = np.arange(1,37)
numpy_A
numpy_m = np.arange(1,22)

In [27]:
A = tf.constant(numpy_A, shape=(3,3,4))
B = tf.constant(numpy_A)
C = tf.constant(numpy_m)
A,B,C

(<tf.Tensor: shape=(3, 3, 4), dtype=int64, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]],
 
        [[25, 26, 27, 28],
         [29, 30, 31, 32],
         [33, 34, 35, 36]]])>,
 <tf.Tensor: shape=(36,), dtype=int64, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36])>,
 <tf.Tensor: shape=(21,), dtype=int64, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21])>)

In [28]:
3*8

24

In [29]:
adim = A.ndim
bdim = B.ndim
adim,bdim

(3, 1)

In [30]:
# Information from sensors
# SHAPE, RANK, AXIS OR DIMENSION, SIZE
shape_a = A.shape
dim_a = A.ndim
size_a = tf.size(A)

shape_a, dim_a, tf.size(size_a)



(TensorShape([3, 3, 4]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [31]:
# Information from sensors
# SHAPE, RANK, AXIS OR DIMENSION, SIZE
shape_a = A.shape
dim_a = A.ndim
size_a = tf.size(A)
dtype_a = A.dtype


print( shape_a)
print(dim_a)
print(size_a)
print(dtype_a)



(3, 3, 4)
3
tf.Tensor(36, shape=(), dtype=int32)
<dtype: 'int64'>


In [32]:
##Crearte a rank 4 tensor  (4 Dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
### Indexing Tensors
### Can be indexed just like lists.

#Get the first 2 elements of each

some_list = [1,2,3,4]
some_list[:2]



[1, 2]

In [34]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:

rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [36]:
# Get the first element from each dimension from each index except  for the final one

rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim


(TensorShape([2, 2]), 2)

In [38]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [39]:
rank_2_tensor[:,-1]
rank_3_tensor = rank_2_tensor[..., tf.newaxis,tf.newaxis]
print(rank_3_tensor)

print (tf.size(rank_3_tensor))

tf.Tensor(
[[[[10]]

  [[ 7]]]


 [[[ 3]]

  [[ 4]]]], shape=(2, 2, 1, 1), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [40]:
tf.expand_dims(rank_3_tensor, axis = 2)

<tf.Tensor: shape=(2, 2, 1, 1, 1), dtype=int32, numpy=
array([[[[[10]]],


        [[[ 7]]]],



       [[[[ 3]]],


        [[[ 4]]]]], dtype=int32)>

In [41]:
tensorb = tf.constant([[10,7],[3,4]])
print(tensorb * 10)
(tensorb)

tf.Tensor(
[[100  70]
 [ 30  40]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [42]:
# we can use the built in tf function directly

tf.multiply(tensorb,200)

x = tf.convert_to_tensor([1, 2, 3, 4, 5])
y = tf.convert_to_tensor(12)
x + y

print (x)
print (y)
print (x + y)


tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor([13 14 15 16 17], shape=(5,), dtype=int32)


In [43]:
tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [44]:
print(tensor)


tensor

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [45]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [46]:
tensor.shape

TensorShape([2, 2])

In [47]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [48]:
Y_T = tf.transpose(Y)

X @ Y_T

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [49]:
print(Y.shape, Y_T.shape)

(3, 2) (2, 3)


In [50]:
xY_multiply = tf.matmul(X,Y_T)

In [51]:
xY_Dot = tf.tensordot(X,Y_T,[[1], [0]])

xY_Dot

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [52]:
X,Y,Y_T,xY_Dot

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]], dtype=int32)>)

In [53]:
y_Reshaped = tf.reshape(Y,(6,1))

print (Y, y_Reshaped)

tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) tf.Tensor(
[[ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]], shape=(6, 1), dtype=int32)


In [54]:
print(tf.transpose(y_Reshaped))
print (Y, y_Reshaped)

tf.Tensor([[ 7  8  9 10 11 12]], shape=(1, 6), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) tf.Tensor(
[[ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]], shape=(6, 1), dtype=int32)


In [55]:
B = Y.dtype

B

tf.int32

In [56]:
tf.__version__

'2.17.0'

In [57]:
#Create a new Tensor with a default datatype (float32)
B = tf.constant([1000.7,7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1000.7,    7.4], dtype=float32)>,
 tf.float32)

In [58]:
C = tf.constant([700,10])
C.dtype

tf.int32

In [59]:
# Change from float32 to float 16
D = tf.cast(B, dtype=tf.float16)
E = tf.cast(B, dtype=tf.int16)
D, D.dtype, E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1000.5,    7.4], dtype=float16)>,
 tf.float16,
 <tf.Tensor: shape=(2,), dtype=int16, numpy=array([1000,    7], dtype=int16)>,
 tf.int16)

Aggegating tensors

In [60]:
# Get the absolute values
D = tf.constant([-7,-10])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

In [61]:
D = tf.constant([-7,-10,2,3,78,12,65,10,2,-8,2.3])
E = tf.constant(np.random.randint(-200,150,size=100))
D
D_min = tf.math.reduce_min(D)
D_max = tf.math.reduce_max(D)
D_mean = tf.math.reduce_mean(D)
D_sum = tf.math.reduce_sum(D)
E_min = tf.math.reduce_min(E)
E_max = tf.math.reduce_max(E)
E_mean = tf.math.reduce_mean(E)
E_sum = tf.math.reduce_sum(E)
E_Float = tf.cast(E,dtype=tf.float32)
E_Stddev = tf.math.reduce_std(E_Float)
E_Var = tf.math.reduce_variance(E_Float)
D,D_min, D_max, D_mean, D_sum, E, E_min, E_max, E_mean, E_sum, E_Float, E_Stddev, E_Var




(<tf.Tensor: shape=(11,), dtype=float32, numpy=
 array([ -7. , -10. ,   2. ,   3. ,  78. ,  12. ,  65. ,  10. ,   2. ,
         -8. ,   2.3], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-10.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=78.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=13.572727>,
 <tf.Tensor: shape=(), dtype=float32, numpy=149.3>,
 <tf.Tensor: shape=(100,), dtype=int64, numpy=
 array([ -91, -144,  -11, -113,  130,  147,  -60,   -5, -102,    0,   45,
          90, -148,    8, -148,  -38,   86,  -82,  -58,   88,  104,  -78,
         121,   39,  -40,   91,  -24,   68,  -67, -114,  -40, -144,   99,
          76,   96,   20,  147,   98,  107,  -60, -115,  -91, -128,   58,
         -88,   22,  -12,  -78,  101, -140,   47,  -44, -163,  -76,  -17,
          97,   17,  139,   30,   30, -148, -175,  -16,  -18,   91, -175,
         -83, -198,  -95,  -34,  -57, -149, -152, -116, -128,   86, -198,
        -177,  -82, -112,   50,   90,  -10,  119,  -61,   -2, -17

In [62]:
tf.math.reduce_variance(D)

<tf.Tensor: shape=(), dtype=float32, numpy=796.5348>

In [63]:
# Create a new tensor for finding positional mion and maximum

tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [64]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [65]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [66]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [67]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [68]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [69]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [70]:
# SQUEEZING ---Create a new tensor to get started

tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [71]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [72]:
G_squeezed = tf.squeeze(G)

G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [73]:
G_squeezed.shape

TensorShape([50])

In [74]:
some_list = [0,1,2,3,4,5,6,7,8]

In [75]:
tf.one_hot(some_list,depth =4)

<tf.Tensor: shape=(9, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [76]:
H = tf.random.uniform(shape = [5, 300])
H

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
        0.9212563 ],
       [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
        0.51477313],
       [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
        0.9892651 ],
       [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
        0.8280058 ],
       [0.36690474, 0.9200133 , 0.9646884 , ..., 0.69012   , 0.7137332 ,
        0.2584542 ]], dtype=float32)>

In [77]:
samples = tf.random.poisson([10], [0.5, 2.5], seed = 0.16)
samples

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[3., 1.],
       [2., 4.],
       [1., 7.],
       [0., 3.],
       [2., 4.],
       [1., 4.],
       [0., 3.],
       [1., 2.],
       [0., 0.],
       [0., 1.]], dtype=float32)>